title: "Edson Lucas"
logo: /assets/img/me.png
description: Edson Ramiro Lucas Filho.
email: edson.lucas@cut.ac.cy
theme: jekyll-theme-minimal
show_downloads: false
twitter_username: edsonrlucas
google_analytics: UA-55680075-1

plugins:
  - jekyll-feed
