
- type: Reviewer
  event: Big Data Research Journal, 2022.
- type: External Reviewer
  event: International Conference on Very Large Data Bases, 2022.
- type: External Reviewer
  event: International Conference on Very Large Data Bases, 2021.
- type: External Reviewer
  event: International Conference on Cognitive Machine Intelligence, 2021.
- type: External Reviewer
  event: International Conference on Extending Database Technology, 2021.
- type: External Reviewer
  event: Expert Systems with Applications, 2020.
- type: External Reviewer
  event: Computer Science and Information Systems journal, 2016.
- type: External Reviewer
  event: Escola Regional de Banco de Dados, 2016.
- type: Student Volunteer
  event: VLDB 2018.

